[package]
# required
name = "r_time"

# required
type = "lib"

# required
build = "make"

# required
repository = ""

# required
version = "0.1.0"

# optional
description = ""

# optional
homepage = ""

# optional
authors = ["bdowns"]

# required even if nothing listed
[dependencies]

